// ─── MOCK DATA ────────────────────────────────────────────────────

export const MODULOS_MOCK = [
  {
    id: "mod-01",
    titulo: "El silencio de la mirada",
    descripcion: "Antes de pintar, mirar. Aprender a detenerse, recorrer una imagen con la atención y registrar lo que se siente antes de lo que se piensa.",
    orden: 1, estado: "publicado", duracion: "2 semanas",
    imagen_url: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80",
    objetivos: ["Desarrollar la capacidad de observación prolongada", "Registrar sensaciones antes de juicios", "Construir un vocabulario visual personal"],
    ejercicio_titulo: "El ejercicio del minuto",
    ejercicio_descripcion: "Durante 7 días, dedica 10 minutos a mirar un mismo objeto. Sin dibujar, sin fotografiar. Solo mirar. Al final, escribe lo que viste.",
    ejercicio_deadline: "20 de Octubre 2026",
    contenidos: [
      { tipo: "video", titulo: "Introducción al módulo", url: "https://www.youtube.com/embed/dQw4w9WgXcQ", orden: 1 },
      { tipo: "texto", titulo: "La mirada como acto creativo", texto: "Todo comienza con la mirada. Antes del pincel, antes del lienzo, antes de cualquier técnica, está el acto de ver. Pero no cualquier tipo de ver: una mirada detenida, paciente, que se permite recorrer sin prisa.\n\nEn este primer módulo, vamos a entrenar esa capacidad. Vamos a aprender a detener el tiempo y a prestar atención a lo que normalmente pasamos por alto.", orden: 2 },
      { tipo: "pdf", titulo: "Guía de observación visual", url: "#", orden: 3 },
      { tipo: "zoom", titulo: "Encuentro virtual — Módulo 1", url: "https://zoom.us/j/ejemplo", orden: 4 },
    ],
  },
  {
    id: "mod-02",
    titulo: "La composición y el equilibrio",
    descripcion: "Reglas para romperlas. Usar la geometría como punto de partida, y luego desplazar, recortar, equilibrar por instinto.",
    orden: 2, estado: "publicado", duracion: "2 semanas",
    imagen_url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
    objetivos: ["Comprender las reglas clásicas de composición", "Aprender a romperlas con intención", "Desarrollar el equilibrio por instinto"],
    ejercicio_titulo: "Composición con restricciones",
    ejercicio_descripcion: "Crea 5 composiciones usando solo líneas horizontales y verticales. Luego, crea 5 más rompiendo esa regla.",
    ejercicio_deadline: "03 de Noviembre 2026",
    contenidos: [
      { tipo: "video", titulo: "La regla de los tercios", url: "https://www.youtube.com/embed/dQw4w9WgXcQ", orden: 1 },
      { tipo: "texto", titulo: "El equilibrio asimétrico", texto: "El equilibrio no siempre significa simetría. A veces, una imagen puede sentirse equilibrada aunque los elementos no estén distribuidos uniformemente.", orden: 2 },
    ],
  },
  {
    id: "mod-03",
    titulo: "El color y su poética",
    descripcion: "El color no decora: dice. Cómo construir una paleta con intención, mantener la coherencia y dejar que el contraste cuente la historia.",
    orden: 3, estado: "publicado", duracion: "2 semanas",
    imagen_url: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80",
    objetivos: ["Comprender la psicología del color", "Construir paletas con intención", "Usar el contraste como narrativa"],
    ejercicio_titulo: "Paleta emocional",
    ejercicio_descripcion: "Elige una emoción y crea una paleta de 5 colores que la represente. Justifica cada elección.",
    ejercicio_deadline: "17 de Noviembre 2026",
    contenidos: [{ tipo: "video", titulo: "El color como lenguaje", url: "https://www.youtube.com/embed/dQw4w9WgXcQ", orden: 1 }],
  },
  {
    id: "mod-04",
    titulo: "La materia y la textura",
    descripcion: "Capas, impasto, transparencias. Cómo la textura modifica la luz y cómo la materia se convierte en narrativa.",
    orden: 4, estado: "publicado", duracion: "2 semanas",
    imagen_url: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80",
    objetivos: ["Explorar técnicas de textura", "Comprender cómo la materia modifica la luz"],
    ejercicio_titulo: "Experimento matérico",
    ejercicio_descripcion: "Crea una pieza usando al menos tres materiales distintos. Documenta el proceso.",
    ejercicio_deadline: "01 de Diciembre 2026",
    contenidos: [],
  },
  {
    id: "mod-05",
    titulo: "La forma y la abstracción",
    descripcion: "Simplificar sin perder la emoción. Ejercicios de reducción, ritmo y silencio para que la forma respire.",
    orden: 5, estado: "borrador", duracion: "2 semanas",
    imagen_url: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800&q=80",
    objetivos: ["Reducir formas complejas", "Encontrar el ritmo visual"],
    ejercicio_titulo: "Reducción formal",
    ejercicio_descripcion: "Toma una imagen figurativa y redúcela a sus formas esenciales en 5 pasos.",
    ejercicio_deadline: "15 de Diciembre 2026",
    contenidos: [],
  },
  {
    id: "mod-06",
    titulo: "La luz y la atmósfera",
    descripcion: "La luz como protagonista. Cómo capturar la atmósfera, jugar con sombras y crear profundidad emocional.",
    orden: 6, estado: "borrador", duracion: "2 semanas",
    imagen_url: "https://images.unsplash.com/photo-1490750967868-88df5691cc95?w=800&q=80",
    objetivos: ["Capturar la atmósfera lumínica", "Usar sombras como herramienta narrativa"],
    ejercicio_titulo: "Estudio de luz",
    ejercicio_descripcion: "Fotografía el mismo espacio a distintas horas del día. Elige una y tradúcela a pintura.",
    ejercicio_deadline: "05 de Enero 2027",
    contenidos: [],
  },
  {
    id: "mod-07",
    titulo: "La naturaleza como espejo",
    descripcion: "El paisaje interior y exterior. Aprender a leer la naturaleza como metáfora y traducirla en imágenes propias.",
    orden: 7, estado: "borrador", duracion: "2 semanas",
    imagen_url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    objetivos: ["Leer el paisaje como metáfora", "Desarrollar un lenguaje visual propio"],
    ejercicio_titulo: "El paisaje interior",
    ejercicio_descripcion: "Sal a un espacio natural. Escribe cómo se siente. Luego pinta desde esa escritura.",
    ejercicio_deadline: "19 de Enero 2027",
    contenidos: [],
  },
  {
    id: "mod-08",
    titulo: "La obra y su sentido",
    descripcion: "Del proceso al resultado. Cómo encontrar la intención detrás de cada obra y darle cierre sin perder la apertura.",
    orden: 8, estado: "borrador", duracion: "2 semanas",
    imagen_url: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    objetivos: ["Articular la intención creativa", "Construir una obra con coherencia"],
    ejercicio_titulo: "Obra final",
    ejercicio_descripcion: "Crea una obra que integre todo lo aprendido. Presenta con un texto de 200 palabras.",
    ejercicio_deadline: "26 de Enero 2027",
    contenidos: [],
  },
];

export const SOLICITUDES_MOCK = [
  { id: "sol-01", nombre: "María García", email: "maria@ejemplo.com", telefono: "+54 11 1234-5678", pais: "Argentina", experiencia: "Llevo 3 años pintando acuarela de forma autodidacta.", interes: "Quiero desarrollar una voz visual propia.", estado: "pendiente", link_pago_enviado: false, created_date: "2026-02-20T10:00:00Z" },
  { id: "sol-02", nombre: "Carlos Ruiz", email: "carlos@ejemplo.com", telefono: "+34 612 345 678", pais: "España", experiencia: "Estudio diseño gráfico, nunca hice pintura.", interes: "Me interesa entender el color desde otro lugar.", estado: "pendiente", link_pago_enviado: false, created_date: "2026-02-21T14:30:00Z" },
  { id: "sol-03", nombre: "Ana López", email: "ana@ejemplo.com", telefono: "+56 9 8765 4321", pais: "Chile", experiencia: "Soy fotógrafa profesional hace 5 años.", interes: "Quiero traducir mi ojo fotográfico a la pintura.", estado: "aprobado", link_pago_enviado: true, created_date: "2026-02-18T09:15:00Z" },
  { id: "sol-04", nombre: "Diego Martínez", email: "diego@ejemplo.com", telefono: "+52 55 1234 5678", pais: "México", experiencia: "Ninguna experiencia previa.", interes: "Siempre quise pintar pero nunca lo hice.", estado: "rechazado", link_pago_enviado: false, created_date: "2026-02-15T16:00:00Z" },
  { id: "sol-05", nombre: "Laura Sánchez", email: "laura@ejemplo.com", telefono: "+54 351 456 7890", pais: "Argentina", experiencia: "Ilustradora digital hace 2 años.", interes: "Explorar el mundo analógico y la textura real.", estado: "pendiente", link_pago_enviado: false, created_date: "2026-02-22T11:45:00Z" },
];

export const ESTUDIANTES_MOCK = [
  { id: "est-01", nombre: "Ana López", email: "ana@ejemplo.com", pais: "Chile", estado_pago: "pagado", monto_pagado: 350, metodo_pago: "Stripe", fecha_pago: "2026-02-19", fecha_inscripcion: "2026-02-20", activo: true },
  { id: "est-02", nombre: "Roberto Vega", email: "roberto@ejemplo.com", pais: "Colombia", estado_pago: "pagado", monto_pagado: 350, metodo_pago: "Stripe", fecha_pago: "2026-02-10", fecha_inscripcion: "2026-02-11", activo: true },
  { id: "est-03", nombre: "Fernanda Costa", email: "fernanda@ejemplo.com", pais: "Brasil", estado_pago: "pagado", monto_pagado: 350, metodo_pago: "Transferencia", fecha_pago: "2026-02-05", fecha_inscripcion: "2026-02-06", activo: true },
  { id: "est-04", nombre: "Tomás Herrera", email: "tomas@ejemplo.com", pais: "Argentina", estado_pago: "no_pagado", monto_pagado: 0, fecha_inscripcion: "2026-02-22", activo: true },
];

export const PAGOS_MOCK = [
  { id: "pag-01", estudiante_nombre: "Ana López", estudiante_email: "ana@ejemplo.com", monto: 350, moneda: "USD", proveedor: "Stripe", referencia_externa: "pi_3N...", estado: "completado", fecha_pago: "2026-02-19" },
  { id: "pag-02", estudiante_nombre: "Roberto Vega", estudiante_email: "roberto@ejemplo.com", monto: 350, moneda: "USD", proveedor: "Stripe", referencia_externa: "pi_4M...", estado: "completado", fecha_pago: "2026-02-10" },
  { id: "pag-03", estudiante_nombre: "Fernanda Costa", estudiante_email: "fernanda@ejemplo.com", monto: 350, moneda: "USD", proveedor: "Transferencia", referencia_externa: "TRF-001", estado: "completado", fecha_pago: "2026-02-05" },
];

export const PROGRESO_MOCK = [
  { estudiante_id: "est-01", modulo_id: "mod-01", porcentaje: 100, completado: true, ultima_actividad: "2026-02-21" },
  { estudiante_id: "est-01", modulo_id: "mod-02", porcentaje: 60, completado: false, ultima_actividad: "2026-02-23" },
  { estudiante_id: "est-02", modulo_id: "mod-01", porcentaje: 100, completado: true, ultima_actividad: "2026-02-15" },
  { estudiante_id: "est-02", modulo_id: "mod-02", porcentaje: 100, completado: true, ultima_actividad: "2026-02-20" },
  { estudiante_id: "est-02", modulo_id: "mod-03", porcentaje: 30, completado: false, ultima_actividad: "2026-02-23" },
  { estudiante_id: "est-03", modulo_id: "mod-01", porcentaje: 100, completado: true, ultima_actividad: "2026-02-12" },
  { estudiante_id: "est-04", modulo_id: "mod-01", porcentaje: 0, completado: false, ultima_actividad: null },
];

export const CONFIG_MOCK = {
  nombre_curso: "Poética de la Mirada",
  descripcion_curso: "Un curso para aprender a ver antes de pintar. Ocho módulos, encuentros virtuales y tiempo de decantación.",
  precio_curso: 350,
  moneda: "USD",
  nombre_profesor: "Ernesto Engel",
  bio_profesor: "Artista visual y docente. Su trabajo explora el paisaje, la memoria y la pintura como acto de atención.",
  foto_profesor_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
  email_contacto: "hola@poeticadelamirada.com",
  whatsapp_numero: "+54 9 11 1234-5678",
  instagram_url: "https://instagram.com/poeticadelamirada",
  link_pago: "https://buy.stripe.com/ejemplo",
  link_formulario: "https://forms.gle/P2qtnPHpnqpDqjjFA",
  cupos_totales: 12,
  fecha_inicio: "6 de Octubre 2026",
};